# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the
# database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Bank.create([
  { cod: '001', name: 'BANCO DO BRASIL S.A.' },
  { cod: '003', name: 'BANCO DA AMAZONIA S.A.' },
  { cod: '004', name: 'BANCO DO NORDESTE DO BRASIL S.A.' },
  { cod: '012', name: 'BANCO STANDARD DE INVESTIMENTOS S.A.' },
  { cod: '014', name: 'NATIXIS BRASIL S.A. BANCO MÚLTIPLO' }, 
  { cod: '019', name: 'BANCO AZTECA DO BRASIL S.A.' }, 
  { cod: '021', name: 'BANESTES S.A. BANCO DO ESTADO DO ESPIRITO SANTO' }, 
  { cod: '024', name: 'BANCO DE PERNAMBUCO S.A. - BANDEPE' }, 
  { cod: '025', name: 'BANCO ALFA S.A.' }, 
  { cod: '029', name: 'BANCO BANERJ S.A.' }, 
  { cod: '031', name: 'BANCO BEG S.A.' }, 
  { cod: '033', name: 'BANCO SANTANDER (BRASIL) S.A.' }, 
  { cod: '036', name: 'BANCO BRADESCO BBI S.A.' }, 
  { cod: '037', name: 'BANCO DO ESTADO DO PARÁ S.A.' }, 
  { cod: '040', name: 'BANCO CARGILL S.A.' }, 
  { cod: '041', name: 'BANCO DO ESTADO DO RIO GRANDE DO SUL S.A.' }, 
  { cod: '044', name: 'BANCO BVA S.A.' }, 
  { cod: '045', name: 'BANCO OPPORTUNITY S.A.' }, 
  { cod: '047', name: 'BANCO DO ESTADO DE SERGIPE S.A.' }, 
  { cod: '062', name: 'HIPERCARD BANCO MÚLTIPLO S.A.' }, 
  { cod: '063', name: 'BANCO IBI S.A. - BANCO MÚLTIPLO' }, 
  { cod: '065', name: 'BANCO LEMON S.A.' }, 
  { cod: '066', name: 'BANCO MORGAN STANLEY S.A.' }, 
  { cod: '069', name: 'BPN BRASIL BANCO MÚLTIPLO S.A.' }, 
  { cod: '070', name: 'BRB - BANCO DE BRASILIA S.A.' }, 
  { cod: '072', name: 'BANCO RURAL MAIS S.A.' }, 
  { cod: '073', name: 'BB BANCO POPULAR DO BRASIL S.A.' }, 
  { cod: '074', name: 'BANCO J. SAFRA S.A.' }, 
  { cod: '075', name: 'BANCO CR2 S/A' }, 
  { cod: '076', name: 'BANCO KDB DO BRASIL S.A.' }, 
  { cod: '077', name: 'BANCO INTERMEDIUM S/A' }, 
  { cod: '078', name: 'BES INVESTIMENTO DO BRASIL S.A. - BANCO DE INVESTIMENTO' }, 
  { cod: '079', name: 'JBS BANCO S/A' }, 
  { cod: '081', name: 'CONCÓRDIA BANCO S.A.' }, 
  { cod: '082', name: 'BANCO TOPÁZIO S.A.' }, 
  { cod: '083', name: 'BANCO DA CHINA BRASIL S.A' }, 
  { cod: '096', name: 'BANCO BM&F DE SERVIÇOS DE LIQUIDAÇÃO E CUSTÓDIA S.A.' }, 
  { cod: '104', name: 'CAIXA ECONOMICA FEDERAL' }, 
  { cod: '107', name: 'BANCO BBM S/A' }, 
  { cod: '151', name: 'BANCO NOSSA CAIXA S.A.' }, 
  { cod: '184', name: 'BANCO ITAÚ BBA S.A.' }, 
  { cod: '204', name: 'BANCO BRADESCO CARTÕES S.A.' }, 
  { cod: '208', name: 'BANCO UBS PACTUAL S.A.' }, 
  { cod: '212', name: 'BANCO MATONE S.A.' }, 
  { cod: '213', name: 'BANCO ARBI S.A.' }, 
  { cod: '214', name: 'BANCO DIBENS S.A.' }, 
  { cod: '215', name: 'BANCO COMERCIAL E DE INVESTIMENTO SUDAMERIS S.A.' }, 
  { cod: '217', name: 'BANCO JOHN DEERE S.A.' }, 
  { cod: '218', name: 'BANCO BONSUCESSO S.A.' }, 
  { cod: '222', name: 'BANCO CALYON BRASIL S.A.' }, 
  { cod: '224', name: 'BANCO FIBRA S.A.' }, 
  { cod: '225', name: 'BANCO BRASCAN S.A.' }, 
  { cod: '229', name: 'BANCO CRUZEIRO DO SUL S.A.' }, 
  { cod: '230', name: 'UNICARD BANCO MÚLTIPLO S.A.' }, 
  { cod: '233', name: 'BANCO GE CAPITAL S.A.' }, 
  { cod: '237', name: 'BANCO BRADESCO S.A.' }, 
  { cod: '241', name: 'BANCO CLASSICO S.A.' }, 
  { cod: '243', name: 'BANCO MÁXIMA S.A.' }, 
  { cod: '246', name: 'BANCO ABC BRASIL S.A.' }, 
  { cod: '248', name: 'BANCO BOAVISTA INTERATLANTICO S.A.' }, 
  { cod: '249', name: 'BANCO INVESTCRED UNIBANCO S.A.' }, 
  { cod: '250', name: 'BANCO SCHAHIN S.A.' }, 
  { cod: '254', name: 'PARANÁ BANCO S.A.' }, 
  { cod: '263', name: 'BANCO CACIQUE S.A.' }, 
  { cod: '265', name: 'BANCO FATOR S.A.' }, 
  { cod: '266', name: 'BANCO CEDULA S.A.' }, 
  { cod: '300', name: 'BANCO DE LA NACION ARGENTINA' }, 
  { cod: '318', name: 'BANCO BMG S.A.' }, 
  { cod: '320', name: 'BANCO INDUSTRIAL E COMERCIAL S.A.' }, 
  { cod: '341', name: 'BANCO ITAÚ S.A.' }, 
  { cod: '366', name: 'BANCO SOCIETE GENERALE BRASIL S.A.' }, 
  { cod: '370', name: 'BANCO WESTLB DO BRASIL S.A.' }, 
  { cod: '376', name: 'BANCO J.P. MORGAN S.A.' }, 
  { cod: '389', name: 'BANCO MERCANTIL DO BRASIL S.A.' }, 
  { cod: '394', name: 'BANCO FINASA BMC S.A.' }, 
  { cod: '399', name: 'HSBC BANK BRASIL S.A. - BANCO MULTIPLO' }, 
  { cod: '409', name: 'UNIBANCO-UNIAO DE BANCOS BRASILEIROS S.A.' }, 
  { cod: '412', name: 'BANCO CAPITAL S.A.' }, 
  { cod: '422', name: 'BANCO SAFRA S.A.' }, 
  { cod: '453', name: 'BANCO RURAL S.A.' }, 
  { cod: '456', name: 'BANCO DE TOKYO-MITSUBISHI UFJ BRASIL S/A' }, 
  { cod: '464', name: 'BANCO SUMITOMO MITSUI BRASILEIRO S.A.' }, 
  { cod: '473', name: 'BANCO CAIXA GERAL - BRASIL S.A.' }, 
  { cod: '477', name: 'CITIBANK N.A.' }, 
  { cod: '479', name: 'BANCO ITAUBANK S.A.' }, 
  { cod: '487', name: 'DEUTSCHE BANK S.A. - BANCO ALEMAO' }, 
  { cod: '488', name: 'JPMORGAN CHASE BANK, NATIONAL ASSOCIATION' }, 
  { cod: '492', name: 'ING BANK N.V.' }, 
  { cod: '494', name: 'BANCO DE LA REPUBLICA ORIENTAL DEL URUGUAY' }, 
  { cod: '495', name: 'BANCO DE LA PROVINCIA DE BUENOS AIRES' }, 
  { cod: '505', name: 'BANCO CREDIT SUISSE (BRASIL) S.A.' }, 
  { cod: '600', name: 'BANCO LUSO BRASILEIRO S.A.' }, 
  { cod: '604', name: 'BANCO INDUSTRIAL DO BRASIL S.A.' }, 
  { cod: '610', name: 'BANCO VR S.A.' }, 
  { cod: '611', name: 'BANCO PAULISTA S.A.' }, 
  { cod: '612', name: 'BANCO GUANABARA S.A.' }, 
  { cod: '613', name: 'BANCO PECUNIA S.A.' }, 
  { cod: '623', name: 'BANCO PANAMERICANO S.A.' }, 
  { cod: '626', name: 'BANCO FICSA S.A.' }, 
  { cod: '630', name: 'BANCO INTERCAP S.A.' }, 
  { cod: '633', name: 'BANCO RENDIMENTO S.A.' }, 
  { cod: '634', name: 'BANCO TRIANGULO S.A.' }, 
  { cod: '637', name: 'BANCO SOFISA S.A.' }, 
  { cod: '638', name: 'BANCO PROSPER S.A.' }, 
  { cod: '641', name: 'BANCO ALVORADA S.A.' }, 
  { cod: '643', name: 'BANCO PINE S.A.' }, 
  { cod: '652', name: 'ITAÚ UNIBANCO BANCO MÚLTIPLO S.A.' }, 
  { cod: '653', name: 'BANCO INDUSVAL S.A.' }, 
  { cod: '654', name: 'BANCO A.J. RENNER S.A.' }, 
  { cod: '655', name: 'BANCO VOTORANTIM S.A.' }, 
  { cod: '707', name: 'BANCO DAYCOVAL S.A.' }, 
  { cod: '719', name: 'BANIF - BANCO INTERNACIONAL DO FUNCHAL (BRASIL), S.A.' }, 
  { cod: '721', name: 'BANCO CREDIBEL S.A.' }, 
  { cod: '734', name: 'BANCO GERDAU S.A' }, 
  { cod: '735', name: 'BANCO POTTENCIAL S.A.' }, 
  { cod: '738', name: 'BANCO MORADA S.A' }, 
  { cod: '739', name: 'BANCO BGN S.A.' }, 
  { cod: '740', name: 'BANCO BARCLAYS S.A.' }, 
  { cod: '741', name: 'BANCO RIBEIRAO PRETO S.A.' }, 
  { cod: '743', name: 'BANCO SEMEAR S.A.' }, 
  { cod: '745', name: 'BANCO CITIBANK S.A.' }, 
  { cod: '746', name: 'BANCO MODAL S.A.' }, 
  { cod: '747', name: 'BANCO RABOBANK INTERNATIONAL BRASIL S.A.' }, 
  { cod: '748', name: 'BANCO COOPERATIVO SICREDI S.A.' }, 
  { cod: '749', name: 'BANCO SIMPLES S.A.' }, 
  { cod: '751', name: 'DRESDNER BANK BRASIL S.A. BANCO MULTIPLO' }, 
  { cod: '752', name: 'BANCO BNP PARIBAS BRASIL S.A.' }, 
  { cod: '753', name: 'NBC BANK BRASIL S. A. - BANCO MÚLTIPLO' }, 
  { cod: '756', name: 'BANCO COOPERATIVO DO BRASIL S.A. - BANCOOB' }, 
  { cod: '757', name: 'BANCO KEB DO BRASIL S.A.' }
])
